### ISSUE TITLE
update your flutter_exoplayer dependency

### ISSUE THREAD

**Issue by danielR2001** [karnadii/flutter_visualizers_test#1]
Hii I've finally added my package to dart packages, so I would recommend to you to depend on dart package dependency. [flutter_exoplayer](https://pub.dev/packages/flutter_exoplayer).

**Comment by karnadii** [comment]
yeah, thanks. but isn't it the same, using git or pub?

**Comment by danielR2001** [comment]
No, when you use pub you have versions that you don't have in GitHub if you depend on my repository and If I make breaking change your app could crash or wont compile, this wont happen if you use pub package because you need to change versions manually, moreover you give me popularity points that raise my score. ;)
